language: cpp
compiler:
  - gcc
  - clang

before_install: sudo apt-get install libboost-test-dev
script: mkdir build && cd build && cmake -DBUILD_UNITTESTS=ON .. && make && cd unit_tests && ./unit_tests

