language: cpp
compiler:
  - gcc
  - clang

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7 
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.7 libboost-test-dev
 - export CXX=g++-4.7

script: mkdir build && cd build && cmake -DBUILD_UNITTESTS=ON .. && make && cd unit_tests && ./unit_tests

